# Generated by Django 2.2.3 on 2021-04-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
